import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="login-page">
    <div className="form">
      <form className="login-form">
        <input type="text" placeholder="username" />
        <input type="password" placeholder="password" />
        <button>login</button>
        
      </form>
    </div>
  </div>
  );
}
